version: '3'
services:
  app1:
    image: nginx:alpine
    ports:
      - "8081:80"
  app2:
    image: nginx:alpine
    ports:
      - "8082:80"
  app3:
    image: nginx:alpine
    ports:
      - "8083:80"
